import CatalogPage from "./CatalogPage"

export const metadata = {
  title: 'Catalog page',
  description: 'Generated by create next app',
}

export default function Catalog() {
  return (
    <CatalogPage/>
  )
}