
import fetchProductsByCategory from "../fetchProducts";
import GenericListPage from "../GenericListPage";


export const metadata = {
  title: "New Products",
  description: "Generated by create next app",
}

const NewProducts = async ({searchParams}:{searchParams: Promise<{page?: string, itemsPerPage?: string}>}) => {

  return <GenericListPage 
  searchParams={searchParams} 
  props={{
    fetchData: () => fetchProductsByCategory("new"),
    pageTitle: "All New Products",
    basePath: "/new",
    errorMessage: "Error, failed to fetch NEW products"
  }}
  />
};

export default NewProducts;
