import { Suspense } from "react";
import fetchProductsByTag from "../fetchProducts";
import GenericListPage from "../GenericListPage";
import { Loader } from "@/app/components/Loader";

export const metadata = {
  title: "New Products",
  description: "Generated by create next app",
};

const NewProducts = async ({
  searchParams,
}: {
  searchParams: Promise<{ page?: string; itemsPerPage?: string }>;
}) => {
  return (
    <Suspense fallback={<Loader />}>
      <GenericListPage
        searchParams={searchParams}
        props={{
          fetchData: ({ pagination: { startIndex, perPage } }) =>
            fetchProductsByTag("new", { pagination: { startIndex, perPage } }),
          pageTitle: "All New Products",
          basePath: "/new"
        }}
      />
    </Suspense>
  );
};

export default NewProducts;
