import { Suspense } from "react";
import fetchProductsByTag from "../fetchProducts";
import GenericListPage from "../GenericListPage";
import { Loader } from "@/app/components/Loader";


export const metadata ={
  title: "Sales in shop",
  description: "Generated by create next app",
}


const AllSales = async ({searchParams}:{searchParams: Promise<{page?: string, itemsPerPage?: string}>}) => {

  return (
    <Suspense fallback={<Loader/>}>
      <GenericListPage 
  searchParams={searchParams} 
  props={{
    fetchData: ({pagination: {startIndex, perPage}}) => fetchProductsByTag("actions", {pagination: {startIndex, perPage}}),
    pageTitle: "All Sales",
    basePath: "/sales"
  }}
  />
    </Suspense>
  )
};

export default AllSales;
