import fetchProductsByCategory from "../fetchProducts";
import GenericListPage from "../GenericListPage";


export const metadata ={
  title: "Sales in shop",
  description: "Generated by create next app",
}


const AllSales = async ({searchParams}:{searchParams: Promise<{page?: string, itemsPerPage?: string}>}) => {

  return <GenericListPage 
  searchParams={searchParams} 
  props={{
    fetchData: () => fetchProductsByCategory("actions"),
    pageTitle: "All Sales",
    basePath: "/sales",
    errorMessage: "Error, failed to fetch SALE products"
  }}
  />
};

export default AllSales;
